# Site settings
title:       JeffreYu
email:       huiyu219@gmail.com
author:      Hui Yu
description: "Hui Yu's personal blog."
baseurl:     ""
url:         "http://huiyu.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# social
social:
  show: true
  github: huiyu
  stackoverflow:
  twitter:
  google_lus:
  linkedin:
  paypal:

# share
share:
  show: false
  facebook: false
  twitter: false
  google_plus: false
  linkedin: false
  digg: false
  tumblr: false
  stumbleupon: false
  sina_weibo: false

# Build settings
markdown:     kramdown

kramdown:
  syntax_highlighter: 'rouge'
permalink:    pretty
paginate:    10
sass:
  compressed: true

gems: [jekyll-paginate]
